app/views/admin.py
import click
from flask import Blueprint, current_app, render_template

import app.models as db_model
from app import db
from app.api import admin_required

admin_bp = Blueprint("admin", __name__, url_prefix="/admin")


@admin_bp.cli.command("createsuperuser")
def createsuperuser():
    username = click.prompt("Username", type=str)
    password = click.prompt("Password", type=str)

    admin = db_model.User(username=username, is_admin=True)
    admin.set_password(password)

    with current_app.app_context():
        try:
            db.session.add(admin)
            db.session.commit()
            click.echo("Superuser created successfully.")
        except Exception as e:
            db.session.rollback()
            click.echo(f"Error creating superuser: {e}")


@admin_bp.route("/")
@admin_bp.route("/files")
@admin_bp.route("/files/<int:page>")
@admin_required()
def files(page=1):
    files = db_model.File.query.paginate(page=page, per_page=4)
    users = db_model.User.query.all()

    context = {
        "title": "Admin",
        "users": users,
        "files": files.items,
        "page": files.page,
        "pages": files.pages,
        "has_next": files.has_next,
        "has_prev": files.has_prev,
    }
    return render_template("admin/files.html", **context)


@admin_bp.route("/users")
@admin_bp.route("/users/<int:page>")
@admin_required()
def users(page: int = 1):
    users = db_model.User.query.paginate(page=page, per_page=4)

    context = {
        "title": "Admin",
        "users": users.items,
        "page": users.page,
        "pages": users.pages,
        "has_next": users.has_next,
        "has_prev": users.has_prev,
    }
    return render_template("admin/users.html", **context)


@admin_bp.route("/logs")
@admin_bp.route("/logs/<int:page>")
@admin_required()
def logs(page: int = 1):
    logs = db_model.Download.query.order_by(db_model.Download.timestamp.desc()).paginate(page=page, per_page=4)

    context = {
        "title": "Admin",
        "logs": logs.items,
        "page": logs.page,
        "pages": logs.pages,
        "has_next": logs.has_next,
        "has_prev": logs.has_prev,
    }
    return render_template("admin/logs.html", **context)

app/views/auth.py
import uuid

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user

from app import db, login_manager
from app.forms import LoginForm, RegisterForm
from app.models import User

auth_bp = Blueprint("auth", __name__)


@login_manager.user_loader
def load_user(user_id: str) -> User:
    user_id = uuid.UUID(user_id)
    return User.query.filter_by(id=user_id).first()


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            user = db.session.query(User).filter(User.username == form.username.data).first()
            if user and user.check_password(form.password.data):
                login_user(user, remember=True)
                return redirect(url_for("main.index"))
        return redirect(url_for("auth.login"))

    else:
        context = {
            "title": "Log in",
            "form": form,
        }
        return render_template("auth/login.html", **context)


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if request.method == "POST":
        if form.validate_on_submit():
            new_user = User(id=uuid.uuid4(), username=form.username.data)
            new_user.set_password(form.password.data)
            try:
                db.session.add(new_user)
                db.session.commit()
            except Exception as e:
                db.session.rollback()

            login_user(new_user, remember=True)
            return redirect(url_for("main.index"))
        return redirect(url_for("auth.register"))

    else:
        context = {
            "title": "Sign up",
            "form": form,
        }
        return render_template("auth/singup.html", **context)


@auth_bp.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="icon" href="{{url_for('static', filename='img/Logo.svg')}}" type="image/svg+xml">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}" type="text/css">
</head>
<body>

{% with messages = get_flashed_messages(category_filter=["error"]) %}
{% if messages %}
<script>
    alert("{{ messages[0] }}");
</script>
{% endif %}
{% endwith %}

<header>
    <div class="header-container">
        <div class="logo">
            <a href="{{ url_for('main.index') }}">
                <img src="{{url_for('static', filename='img/Logo.svg')}}">
            </a>
        </div>

        {%block header%} {%endblock%}

    </div>
</header>

<main>

    {%block main%} {%endblock%}

</main>

<script src="{{url_for('static', filename='js/script.js')}}"></script>
</body>
</html>

app/templates/baseTable.html
<div class="main-area">
    <div class="content-area">
        {% with messages = get_flashed_messages(category_filter=["message"]) %}
        {% if messages %}
        <div class="message"> {{messages[0]}} </div>
        {% endif %}
        {% endwith %}
        <div class="content-container">

            {% block tableContent %} {% endblock %}

            <div class="footer">
                <div class="pagination">
                    {% if has_prev %}
                    <a class="page-button previous" href="{{ url_for(request.endpoint, page=page-1) }}">
                        <img src="{{url_for('static', filename='img/PreviousPage.svg')}}">
                    </a>
                    {% endif %}
                    <div class="page-number">
                        {% if pages %}
                        <div class="current-page">{{ page }}</div>
                        <div class="page-separator">/</div>
                        <div class="page-count">{{ pages }}</div>
                        {% endif %}
                    </div>
                    {% if has_next %}
                    <a class="page-button next" href="{{ url_for(request.endpoint, page=page+1) }}">
                        <img src="{{url_for('static', filename='img/NextPage.svg')}}">
                    </a>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>

    <div id="overlay" class="overlay" onclick="closeAllDialogs()"></div>

app/templates/header.html
<div class="header-content">

    <div class="header-title">FileHub</div>

    <form class="search" action="{{ url_for('main.index') }}" method="get">
        <button class="search-button" type="submit">
            <img class="search-icon" src="{{url_for('static', filename='img/Search.svg')}}">
        </button>
        <input type="text" name="query">
    </form>

    {% if current_user.is_authenticated %}
    <div class="user-button dropdown-button" onclick="toggleDropdown('userDropdown')">
        <img src="{{url_for('static', filename='img/User.svg')}}">
    </div>

    <div class="dropdown-menu" id="userDropdown">
        <div class="dropdown-content">
            {% if current_user.is_admin %}
            <div class="dropdown-element">
                <a href="{{url_for('admin.files')}}">Admin panel</a>
            </div>
            {% endif %}
            <div class="dropdown-element">
                <a href="{{ url_for('auth.logout') }}">Log out</a>
            </div>
        </div>
    </div>
    {% else %}
    <a class="header-button login" href="{{ url_for('auth.login') }}">Log in</a>
    <a class="header-button sing-up" href="{{ url_for('auth.register') }}">Sing up</a>
    {% endif %}

</div>

app/templates/index.html
{% extends 'base.html' %}

{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% include 'file/table.html' %}
{% endblock %}